sudo: false
dist: trusty
language: node_js
node_js:
  - 'node'
  - 'lts/argon'
install:
  - npm set progress=false
  - npm install
  - npm update
before_script:
  - export CHROME_BIN=/usr/bin/google-chrome
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
addons:
  firefox: latest
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
cache:
  directories:
    - node_modules
