#!/usr/bin/env node
var CommanderWrapper = require('./utils/commander-wrapper');

var program = CommanderWrapper(function(commander) {
  return commander
    .command('build', 'build your packages styles, js, docs, and tests')
    .command('watch', 'watch your packages styles, js, docs, and tests for changes and build')
    .command('clean', 'cleanup temporary files, and build targets')
    .command('start', 'start a development server, and run watch seprately')
    .command('server', 'alias for start')
    .command('test', 'run unit tests')
    .command('lint', 'run eslint with the standard config over files')
    .command('config', 'print out the current configuration object that Spellbook is using')
    .command('release', 'release a new version of your package');
});

