#!/usr/bin/env node
var config = require('./utils/get-config')();
var path = require('path');
var browserifyHelper = require('./utils/browserify-helper');
var exec = require('./utils/exec');
var log = require('./utils/log');
var CommanderWrapper = require('./utils/commander-wrapper');
var GetFiles = require('./utils/get-files');
var Clean = require('./utils/clean');

var program = CommanderWrapper(function(commander) {
  return commander
    .option('-w, --watch', 'incremental rebuild')
    .option('-d, --dist <dir>', 'dir to write output to', path.join(config.dist, 'browser'))
    .arguments('<dir>')
    .action(function(src) {
      this.src = src;
    });
});

if (!program.src) {
  program.src = path.join(config.src, 'js', 'index.js');
}

if(!GetFiles(program.src, 'index.js')) {
  log.fatal('Source directory ' + program.src + ' does not exist or contains no index.js!');
  process.exit(1);
}

Clean(program.dist);
var distFile = path.join(program.dist, config.name);
browserifyHelper({
  dist: distFile,
  src: program.src,
  standalone: true,
  watch: program.watch
});

// we don't want to uglify after watching
if (!program.watch) {

  // remove the last newline in the banner
  // uglify adds it for us
  var banner = config.banner;
  banner = config.banner.replace(/\n$/, '');
  exec([
    'uglifyjs',
    '--compress',
    '--mangle',
    '--in-source-map',
    distFile + '.js.map',
    '--source-map ',
    distFile + '.min.js.map',
    '--source-map-url ',
    path.basename(distFile) + '.min.js.map',
    '--preamble',
    '\'' + banner + '\'',
    '-o',
   distFile + '.min.js',
    '--',
   distFile + '.js'
], {silent: true});
  log.info('Wrote ' + distFile + '.min.js');
  log.info('Wrote ' + distFile + '.min.js.map');
}
