#!/usr/bin/env node
var CommanderWrapper = require('./utils/commander-wrapper');
var RunAll = require('./utils/run-all');

var program = CommanderWrapper(function(commander) {
  return commander
    .option('-w, --watch', 'watch docs for changes and rebuild');
});

var commands = [
  ['sb-build-docs-api'],
  ['sb-build-docs-manual']
];
var args = [];

if (program.watch) {
  args.push('--watch');
}

RunAll(commands, args)
