#!/usr/bin/env node
var path = require('path');
var config = require('./utils/get-config')();
var GetFiles = require('./utils/get-files');
var shelljs = require('shelljs');
var Watch = require('./utils/watch');
var exec = require('./utils/exec');
var log = require('./utils/log');
var CommanderWrapper = require('./utils/commander-wrapper');

var program = CommanderWrapper(function(commander) {
  return commander
    .option('-w, --watch', 'watch docs for changes and rebuild')
    .option('-d, --dist <dir>', 'directory to build api docs to', path.join(config.dist, 'docs', 'api'))
    .arguments('<dir>')
    .action(function(src) {
      this.src = src;
    });
});


if (!program.src) {
  program.src = path.join(config.src, 'js');
}

if (!GetFiles(path.join(program.src, '**', '*.js'))) {
  log.fatal('Source directory ' + program.src + ' does not exist or contains no js files!');
  process.exit(1);
}

var command = [
  'jsdoc', program.src,
  '--configure', 'jsdoc.config.json',
  '-r',
  '-d', program.dist
];

var build = function() {
  shelljs.rm('-rf', program.dist);
  shelljs.mkdir('-p', path.dirname(program.dist));

  log.info('Building...');
  exec(command, {silent: true});
  log.info('Wrote: ' + program.src + ' -> ' + program.dist);
};

if (program.watch) {
  Watch(path.join(program.src, '**', '*.js'), build);
} else {
  build();
}
