#!/usr/bin/env node
var config = require('./utils/get-config')();
var PathExists = require('./utils/path-exists');
var GetPath = require('./utils/get-path');
var RunCommand = require('./utils/run-command');
var path = require('path');
var shelljs = require('shelljs');

var program = require('commander')
  .version(config.sbVersion)
  .option('-w, --watch', 'incremental rebuild')
  .option('-d, --dist <dir>', 'file to write output to')
  .arguments('<glob>')
  .action(function(src) {
    this.src = src;
  })
  .parse(process.argv);

if (!program.src) {
  program.src = path.join(config.src, 'test', '*.test.js')
}

if (!program.dist) {
  program.dist = path.join(config.dist, 'test');
}

var distFile = path.join(program.dist, config.name);
browserifyHelper({
  dist: distFile,
  src: program.src,
  standalone: false,
  watch: program.watch
});
console.log('Wrote ' + distFile + '.js');
console.log('Wrote ' + distFile + '.js.map');
