#!/usr/bin/env node
var CommanderWrapper = require('./utils/commander-wrapper');
var config = require('./utils/get-config')();
var log = require('./utils/log');

var program = CommanderWrapper(function(commander) {
  return commander
    .command('browser', 'build js tests for the browser')
    .command('bundlers', 'build js bundler tests for the browser')
    .command('all', 'build all possible js outputs', {isDefault: true});
});

if (!config.test) {
  log.warn('Unit Test builds are turned off');
  process.exit();
}
