#!/usr/bin/env node
var config = require('./utils/get-config')();
var path = require('path');
var browserifyHelper = require('./utils/browserify-helper');
var exec = require('./utils/exec');
var log = require('./utils/log');
var CommanderWrapper = require('./utils/commander-wrapper');
var PathsExist = require('./utils/paths-exist');
var GetFiles = require('./utils/get-files');
var Watch = require('./utils/watch');
var shelljs = require('shelljs');

var program = CommanderWrapper(function(commander) {
  return commander
    .option('-w, --watch', 'incremental rebuild')
    .option('-d, --dist <dir>', 'dir to write output to', path.join(config.dist, 'browser'))
    .arguments('<dir>')
    .action(function(src) {
      this.src = src;
    });
});

if (!program.src) {
  program.src = path.join(config.src, 'js');
}

if(!GetFiles(path.join(program.src, 'index.js'))) {
  log.fatal('Source directory ' + program.src + ' does not exist or contains no index.js!');
  process.exit(1);
}

var distFile = path.join(program.dist, config.name);
browserifyHelper({
  dist: distFile,
  src: path.join(program.src, 'index.js'),
  standalone: true,
  watch: program.watch
}).then(function() {

  if (!PathsExist(distFile + '.js')) {
    return;
  }
  // we don't want to uglify after watching
  if (program.watch) {
    return;
  }
  // clean
  ['min.js', 'min.js.map'].forEach(function(ext) {
    shelljs.rm('-rf', distFile + ext);
  });

  // remove the last newline in the banner
  // uglify adds it for us
  var banner = config.banner;
  banner = config.banner.replace(/\n$/, '');
  var cmd = [
    'uglifyjs',
    '--compress',
    '--mangle',
    '--in-source-map',
    distFile + '.js.map',
    '--source-map ',
    distFile + '.min.js.map',
    '--source-map-url ',
    path.basename(distFile) + '.min.js.map',
    '--preamble',
    '\'' + banner + '\'',
    '-o',
    distFile + '.min.js',
    '--',
    distFile + '.js'
  ];

  if (config.ie8) {
    cmd.splice(1, 0, '--support-ie8');
  }

  exec(cmd, {silent: true});
  log.info('Wrote: ' + distFile + '.min.js');
  log.info('Wrote: ' + distFile + '.min.js.map');
});

