#!/usr/bin/env node
var path = require('path');
var config = require('./utils/config');
var RunCommand = require('./utils/run-command');
var GetPath = require('./utils/get-path');

require('commander')
  .version(config.sbVersion)
  .option('-w, --watch', 'watch docs for changes and rebuild')
  .parse(process.argv);

RunCommand('rm', '-rf', path.join(config.dist, 'docs'));
RunCommand('mkdir', '-p', path.join(config.dist, 'docs', 'api'));

// TODO: watch with chokidar and --watch for remark

RunCommand('exec', GetPath('remark')
  + ' ' + path.join(config.src, 'docs')
  + ' --use html'
  + ' --no-config'
  + ' --output ' + path.join(config.dist, 'docs')
, {async: true});

// TODO add local config for markdown plugin
RunCommand('exec', GetPath('jsdoc')
  + ' ' + path.join(config.src, 'js')
  + ' -r'
  + ' -d ' + path.join(config.dist, 'docs', 'api')
, {async: true});

RunCommand('exec', GetPath('doctoc')
  + ' ' + path.join(config.path, 'README.md')
, {async: true});
