#!/usr/bin/env node
var path = require('path');
var config = require('./utils/get-config')();
var GetPath = require('./utils/get-path');
var RunCommand = require('./utils/run-command');

var program = require('commander')
  .version(config.sbVersion)
  .option('-w, --watch', 'incrementally rebuild')
  .parse(process.argv);

var commands = [
  GetPath('sb-build-js-browser'),
  GetPath('sb-build-js-npm')
];

commands.forEach(function(command) {
  if (program.watch) {
    command += ' --watch';
  }
  RunCommand('exec', command, {async: true});
});
