#!/usr/bin/env node
var path = require('path');
var config = require('./utils/get-config')();
var GetFiles = require('./utils/get-files');
var Watch = require('./utils/watch');
var log = require('./utils/log');
var Run = require('./utils/run');
var CommanderWrapper = require('./utils/commander-wrapper');
var Promise = require('bluebird');
var PathsExist = require('./utils/paths-exist');
var rimraf = require('rimraf');
var mkdirp = require('mkdirp');

var program = CommanderWrapper(function(commander) {
  return commander
    .option('-w, --watch', 'watch docs for changes and rebuild')
    .option('-d, --dist <dist-dir>', 'directory to build api docs to', path.join(config.dist, 'docs', 'manual'))
    .arguments('<src-dir>')
    .action(function(src) {
      this.src = src;
    });
});

if (!program.src) {
  program.src = config.docs.src;
}

var command = [
  'remark',
  '--no-color',
  '--rc-path', 'remark-build.config.js',
];

var build = function() {
  rimraf.sync(program.dist);
  mkdirp.sync(program.dist);

  var files = GetFiles(path.join(program.src, '**', '*.md'));
  if (!files.length) {
    log.error('Source directory ' + process.src + ' doesnt exist or contains no md files!');
    process.exit(1);
  }

  log.info('Building...');

  var promises = [];

  // we have to build each file individually, as there is no directory style output
  // aka src/docs/test/index.md would flatten to dist/docs/manual/index.html
  // rather than dist/docs/manual/test/index.html
  files.forEach(function(src) {
    var dist = path.dirname(src.replace(program.src, program.dist));

    mkdirp.sync(dist);
    promises.push(Run.one(command.concat([src, '--output', dist]), {silent: true, write: dist}));
  });

  Promise.all(promises).then(function() {
    log.info('Wrote: ' + program.dist);
  });
};

if (program.watch) {
  Watch(path.join(program.src, '**', '*.md'), build);
} else {
  build();
}
