#!/usr/bin/env node
var CommanderWrapper = require('./utils/commander-wrapper');

var program = CommanderWrapper(function(commander) {
  return commander
    .command('browser', 'build js browser output')
    .command('es5', 'build es5 output')
    .command('bundles', 'build rollup, webpack, and browserify test files')
    .command('all', 'build all possible js outputs', {isDefault: true});
});



