#!/usr/bin/env node
var CommanderWrapper = require('./utils/commander-wrapper');
var config = require('./utils/get-config')();
var log = require('./utils/log');

var program = CommanderWrapper(function(commander) {
  return commander
    .command('all', 'run all doc builds', {isDefault: true})
    .command('api', 'run the api doc build')
    .command('manual', 'run the manual doc build');
});

if (!config.docs) {
  log.warn('Docs builds are turned off');
  process.exit();
}
