#!/usr/bin/env node
var path = require('path');
var shelljs = require('shelljs');
var config = require('./utils/get-config')();
var GetFiles = require('./utils/get-files');
var Watch = require('./utils/watch');
var log = require('./utils/log');
var exec = require('./utils/exec');
var CommanderWrapper = require('./utils/commander-wrapper');

var program = CommanderWrapper(function(commander) {
  return commander
    .option('-w, --watch', 'watch docs for changes and rebuild')
    .option('-d, --dist <dir>', 'directory to build api docs to', path.join(config.dist, 'docs', 'manual'))
    .arguments('<dir>')
    .action(function(src) {
      this.src = src;
    });
});

if (!program.src) {
  program.src = path.join(config.src, 'docs');
}

if (!GetFiles(path.join(program.src, '**', '*.md'))) {
  log.error('Source directory ' + process.src + ' doesnt exist or contains no md files!');
  process.exit(1);
}

var command = [
  'remark', program.src,
  '--no-config',
  '--rc-path', 'remark-build.config.js',
  '--output', program.dist
];

var build = function() {
  shelljs.rm('-rf', program.dist);
  shelljs.mkdir('-p', program.dist);

  log.info('Building...');
  exec(command, {silent: true});
  log.info('Wrote: ' + program.src + ' -> ' + program.dist);
};

if (program.watch) {
  Watch(path.join(program.src, '**', '*.md'), build);
} else {
  build();
}
