#!/usr/bin/env node
var config = require('./utils/config');
var PathExists = require('./utils/path-exists');
var shelljs = require('shelljs');
var path = require('path');
var RunCommand = require('./utils/run-command');
var GetPath = require('./utils/get-path');

var program = require('commander')
  .version(config.spellbookVersion)
  .option('-w, --watch', 'incremental rebuild')
  .option('-d, --dist <dist-file>', 'file to write output to')
  .arguments('<src-file>')
  .action(function(src) {
    this.src = src;
  })
  .parse(process.argv);

if (!program.src || !program.dist) {
  console.error('must pass in a src and a dist, see --help for details');
  process.exit(1);
}

if (!PathExists(program.src)) {
  console.error(program.src + ' does not exist!');
  process.exit(1);
}

var dirName = path.dirname(program.dist);
var distFile = path.join(dirName, path.basename(program.dist, path.extname(program.dist)));

RunCommand('rm', '-rf', dirName);
RunCommand('mkdir', '-p', dirName);
var cmd = ''
    + GetPath('node-sass')
    + ' ' + program.src
    + ' ' + distFile + '.css'
    + ' --output-style=compressed'
    + ' --linefeed=lf'
    + ' --sourceMap true'
    + ' --sourceMapContents'
    + ' --sourceMapEmbed';

if (program.watch) {
  cmd += ' --watch';
}

RunCommand('exec', cmd);

if (program.watch) {
  process.exit(0);
}

RunCommand('exec', GetPath('cssnano')
  + ' --safe'
  + ' --sourcemap'
  + ' ' + distFile + '.css'
, {silent: true}).to(distFile + '.min.css');

shelljs.cat(distFile + '.css')
  .exec(GetPath('exorcist') + " '" + distFile + ".css.map'", {silent: true})
  .to(distFile + '.css');

shelljs.cat(distFile + '.min.css')
  .exec(GetPath('exorcist') + " '" + distFile + ".min.css.map'", {silent: true})
  .to(distFile + '.min.css');


