#!/usr/bin/env node
var CommanderWrapper = require('./utils/commander-wrapper');
var Run = require('./utils/run');

var program = CommanderWrapper(function(commander) {
  return commander
    .option('-w, --watch', 'incrementally rebuild');
});

var commands = [
  ['sb-build-lang-copy'],
];

if (program.watch) {
  commands = commands.map(function(command) {
    command.push('--watch');
    return command;
  });
}

Run.parallel(commands);
