#!/usr/bin/env node
var RunAll = require('./utils/run-all');
var CommanderWrapper = require('./utils/commander-wrapper');

var program = CommanderWrapper(function(commander) {
  return commander
    .option('-w, --watch', 'incrementally rebuild');
});

var commands = [
  ['sb-build-js-browser-src'],
  ['sb-build-js-browser-test']
  ['sb-build-js-browser-bundletests']
];
var args = [];

if (program.watch) {
  args.push('--watch');
}

RunAll(commands, args);
