#!/usr/bin/env node
var CommanderWrapper = require('./utils/commander-wrapper');

var program = CommanderWrapper(function(commander) {
  return commander
    .command('all', 'run all commands', {isDefault: true})
    .command('sass', 'run sass build');
});
