#!/usr/bin/env node
var path = require('path');
var config = require('./utils/get-config')();
var GetPath = require('./utils/get-path');
var PathExists = require('./utils/path-exists');
var shelljs = require('shelljs');
var Watch = require('./utils/watch');

var program = require('commander')
  .version(config.sbVersion)
  .option('-w, --watch', 'watch docs for changes and rebuild')
  .option('-d, --dist <dist-dir>', 'directory to build api docs to')
  .arguments('<src-dir>')
  .action(function(src) {
    this.src = src;
  })
  .parse(process.argv);

if (!program.dist) {
  program.dist = path.join(config.dist, 'docs', 'api');
}

if (!program.src) {
  program.src = path.join(config.src, 'js');
}

if (PathExists(program.dist)) {
  shelljs.rm('-rf', program.dist);
}

shelljs.mkdir('-p', program.dist);

var command = GetPath('jsdoc')
  + ' ' + program.src
  + ' --configure ' + GetPath('jsdoc.config.json')
  + ' -r'
  + ' -d ' + program.dist;

console.log('building docs from ' + program.src + ' to ' + program.dist);
shelljs.exec(command);

if (program.watch) {
  Watch(path.join(program.src, '**', '*.js'), command);
}

