#!/usr/bin/env node
var config = require('./utils/get-config')();
var path = require('path');
var browserifyHelper = require('./utils/browserify-helper');
var CommanderWrapper = require('./utils/commander-wrapper');
var GetFiles = require('./utils/get-files');
var log = require('./utils/log');

var program = CommanderWrapper(function(commander) {
  return commander
    .option('-w, --watch', 'incremental rebuild')
    .option('-d, --dist <dir>', 'file to write output to', config.test.dist)
    .arguments('<dir>')
    .action(function(src) {
      this.src = src;
    });
});

if (!program.src) {
  program.src = config.test.src;
}

if(!GetFiles(path.join(program.src, '**', '*.test.js'))) {
  log.fatal('Source directory ' + program.src + ' does not exist or contains no test.js files!');
  process.exit(1);
}

log.info('Building...');
browserifyHelper({
  dist: path.join(program.dist, config.name + '.test'),
  src: path.join(program.src, '**', '*.test.js'),
  standalone: false,
  watch: program.watch,
  internalMap: true
});
