#!/usr/bin/env node
var path = require('path');
var config = require('./utils/config');
var GetBinPath = require('./utils/get-bin-path');
var RunCommand = require('./utils/run-command');


// TODO: skip specific build step
var program = require('commander')
  .version(config.sbVersion)
  .option('-w, --watch', 'incrementally rebuild')
  .parse(process.argv);

var commands = [];

// build tests
commands.push(''
  + GetBinPath('sb-build-js-browser')
  + ' --dont-min'
  + ' --dist ' + path.join(config.dist, 'test', 'bundle.js')
  + ' ' + path.join(config.src, 'test', '**', '*.test.js')
);

// build browser dist
commands.push(''
  + GetBinPath('sb-build-js-browser')
  + ' --dist ' + path.join(config.dist, 'browser', config.name + '.js')
  + ' ' + path.join(config.src, 'js', 'index.js')
);

// build npm dist
commands.push(''
  + GetBinPath('sb-build-js-npm')
  + ' --dist ' + path.join(config.dist, 'npm')
  + ' ' + path.join(config.src, 'js')
);

for (var i = 0; i < commands.length; i++) {
  // add watch flag
  if (program.watch) {
    commands[i] += ' --watch';
  }
  RunCommand('exec', commands[i], {async: true});
}
