#!/usr/bin/env node
var CommanderWrapper = require('./utils/commander-wrapper');
var RunAll = require('./utils/run-all');

var program = CommanderWrapper(function(commander) {
  return commander
    .option('-w, --watch', 'watch files for changes');
});

var commands = [
  ['sb-build-css-css']
  ['sb-build-css-sass']
];
var args = [];

if (program.watch) {
  args.push('--watch');
}

RunAll(commands, args);
