#!/usr/bin/env node
var CommanderWrapper = require('./utils/commander-wrapper');

var program = CommanderWrapper(function(commander) {
  return commander
    .command('all', 'build all browser bundles', {isDefault: true})
    .command('main', 'build main code browser bundle')
    .command('test', 'build unit test browser bundle');
});

