#!/usr/bin/env node
var RunAll = require('./utils/run-all');
var exec = require('./utils/exec');
var CommanderWrapper = require('./utils/commander-wrapper');
var config = require('./utils/get-config')();
var PathsExist = require('./utils/paths-exist')();
var log = require('./utils/log');

var program = CommanderWrapper(function(commander) {
  return commander
    .option('-w, --watch', 'watch files for changes and rebuild');
});

exec('sb-clean');
var commands = [];
var args = [];

['js', 'test', 'css', 'docs', 'lang'].forEach(function(buildName) {
  if (!config[buildName] || !config[buildName].src) {
    log.debug(buildName + ' build is turned off in packageg.json.');
  } else if (!PathsExist(config[buildName].src)) {
    log.debug(buildName + ' build will not run as src dir ' + config[buildName].src + ' does not exist.');
  } else {
    commands.push(['sb-build-' + buildName + '-all']);
  }
});

if (program.watch) {
  args.push('--watch');
}

RunAll(commands, args);
