#!/usr/bin/env node
var CommanderWrapper = require('./utils/commander-wrapper');

var program = CommanderWrapper(function(commander) {
  return commander
    .command('copy', 'copy src lang folder to dist')
    .command('all', 'run all build lang commands', {isDefault: true});
});

