#!/usr/bin/env node
var config = require('./utils/get-config')();
var PathExists = require('./utils/path-exists');
var GetPath = require('./utils/get-path');
var path = require('path');
var shelljs = require('shelljs');

var program = require('commander')
  .version(config.sbVersion)
  .option('-w, --watch', 'incremental rebuild')
  .option('-d, --dist <dir>', 'directory to write output to')
  .arguments('<src-dir>')
  .action(function(src) {
    this.src = src;
  })
  .parse(process.argv);

if (!program.src) {
  program.src = path.join(config.src, 'js');
}

if (!program.dist) {
  program.dist = path.join(config.dist, 'npm');
}

shelljs.rm('-rf', program.dist);
shelljs.mkdir('-p', program.dist);

var babelPreset = config.ie8 ? GetPath('babel-preset-ie8.config.js') : GetPath('babel-preset.config.js');

var cmd = GetPath('babel') + ' '
  + '-d ' + program.dist + ' '
  + ' --presets ' + babelPreset
  + ' ' + program.src;

if (program.watch) {
  cmd += ' --watch';
}

shelljs.exec(cmd);
