#!/usr/bin/env node
var exec = require('./utils/exec');
var CommanderWrapper = require('./utils/commander-wrapper');

var program = CommanderWrapper(function(commander) {
  return commander
    .option('-w, --watch', 'incrementally rebuild');
});

var args = [];

if (program.watch) {
  args.push('--watch');
}
exec(['sb-build-js-npm'].concat(args), {async: true}).then(function() {
  return exec(['sb-build-js-bundles'].concat(args), {async: true});
});

exec(['sb-build-js-browser-all'].concat(args), {async: true});
