#!/usr/bin/env node
var RunAll = require('./utils/run-all');
var exec = require('./utils/exec');
var log = require('./utils/log');
var CommanderWrapper = require('./utils/commander-wrapper');
var config = require('./utils/get-config')();

var program = CommanderWrapper(function(commander) {
  return commander
    .option('-w, --watch', 'watch files for changes and rebuild')
});

exec('sb-clean');
var commands = [];
var args = []

if (config.js) {
  commands.push(['sb-build-js-all']);
}

if (config.css) {
  commands.push(['sb-build-css-all']);
}

if (config.docs) {
  commands.push(['sb-build-docs-all']);
}

if (config.i18n) {
  commands.push(['sb-build-i18n']);
}

if (program.watch) {
  args.push('--watch');
}

RunAll(commands, args);
