#!/usr/bin/env node
var exec = require('./utils/exec');
var CommanderWrapper = require('./utils/commander-wrapper');
var RunAll = require('./utils/run-all');

var program = CommanderWrapper(function(commander) {
  return commander
    .option('-w, --watch', 'incrementally rebuild');
});

var commands = [
  ['sb-build-lang-copy'],
];
var args = [];

if (program.watch) {
  args.push('--watch');
}

RunAll(commands, args);
