#!/usr/bin/env node
var CommanderWrapper = require('./utils/commander-wrapper');

var program = CommanderWrapper(function(commander) {
  return commander
    .command('js', 'build js for the project')
    .command('test', 'build test js for the project')
    .command('css', 'build css for the project')
    .command('docs', 'build docs for the project')
    .command('lang', 'build lang for the project')
    .command('all', 'run all builds for the project', {isDefault: true});
});

