#!/usr/bin/env node
var CommanderWrapper = require('./utils/commander-wrapper');
var Run = require('./utils/run');

var program = CommanderWrapper(function(commander) {
  return commander
    .option('-w, --watch', 'watch docs for changes and rebuild');
});

var commands = [
  ['sb-build-docs-api'],
  ['sb-build-docs-manual']
];

if (program.watch) {
  commands = commands.map(function(command) {
    command.push('--watch');
    return command;
  });
}

Run.all(commands);
