#!/usr/bin/env node
var config = require('./utils/get-config')();
var PathExists = require('./utils/path-exists');
var RunCommand = require('./utils/run-command');
var GetPath = require('./utils/get-path');
var path = require('path');

var program = require('commander')
  .version(config.sbVersion)
  .option('-w, --watch', 'incremental rebuild')
  .option('-d, --dist <dir>', 'directory to write output to')
  .arguments('<src-dir>')
  .action(function(src) {
    this.src = src;
  })
  .parse(process.argv);

if (!program.src) {
  program.src = path.join(config.src, 'js');
}

if (!program.dist) {
  program.dist = path.join(config.dist, 'npm');
}

// TODO: noderify
// TODO: ie8 support
RunCommand('rm', '-rf', program.dist);
RunCommand('mkdir', '-p', program.dist);

var cmd = GetPath('babel') + ' '
  + "-d '" + program.dist + "' "
  + "--presets es2015 "
  + "--plugins transform-object-assign "
  + program.src;

if (program.watch) {
  cmd += ' --watch';
}

RunCommand('exec', cmd);
