#!/usr/bin/env node
var Run = require('./utils/run');
var CommanderWrapper = require('./utils/commander-wrapper');

var program = CommanderWrapper(function(commander) {
  return commander
    .option('-w, --watch', 'incrementally rebuild');
});

var commands = [
  ['sb-build-test-bundlers'],
  ['sb-build-test-browser'],
];

if (program.watch) {
  commands = commands.map(function(command) {
    command.push('--watch');
    return command;
  });
}

Run.all(commands);
