#!/usr/bin/env node
var config = require('./utils/get-config')();
var PathExists = require('./utils/path-exists');
var shelljs = require('shelljs');
var glob = require('glob');
var path = require('path');
var log = require('./utils/log');
var CommanderWrapper = require('./utils/commander-wrapper');

var program = CommanderWrapper(function(commander) {
  return commander
    .option('-d, --dry-run', 'see what would happen when you run clean')
    .option('-c, --cache', 'clear the  cache folder too')
    .option('-q, --quiet', 'dont log any output, other than errors');
});

if (program.quiet && program.dryRun) {
  log.fatal('--dry-run should not be used with --quiet');
  process.exit(1);
}

var files = glob.sync(path.join(config.path, '**',  'npm-debug.log'), {ignore: '**/node_modules/**'});
files.push(config.dist);

if (program.cache) {
  files.push(config.cache);
}
files.forEach(function(file) {
  if (!PathExists(file)) {
    return;
  }
  if (!program.quiet) {
    log.info('removing ' + file);
  }
  if (!program.dryRun) {
    shelljs.rm('-rf', file);
  }
});
