#!/usr/bin/env node
var config = require('./utils/get-config')();
var path = require('path');
var eslintHelper = require('./utils/eslint-helper');
var CommanderWrapper = require('./utils/commander-wrapper');

var program = CommanderWrapper(function(commander) {
  return commander
    .command('src', 'lint src files')
    .command('test', 'lint test js files')
    .command('all', 'run all', {isDefault: true});
});
