#!/usr/bin/env node
var config = require('./utils/get-config')();

var program = require('commander')
  .version(config.sbVersion)
  .command('md', 'lint markdown files')
  .command('examples', 'lint js examples in markdown files')
  .command('all', 'run all', {isDefault: true})
  .parse(process.argv);
