#!/usr/bin/env node
var config = require('./utils/get-config')();
var path = require('path');
var eslintHelper = require('./utils/eslint-helper');
var CommanderWrapper = require('./utils/commander-wrapper');
var log = require('./utils/log');

var program = CommanderWrapper(function(commander) {
  return commander
    .option('-w, --watch', 'watch files for changes and re-lint')
    .option('-e, --errors', 'only log errors')
    .option('-f, --fix', 'fix problems automatically')
    .arguments('<glob-or-file...>')
    .action(function(src) {
      this.src = src;
    });

});

if (!program.src) {
  program.src = [path.join(config.lang.src, '**', '*.json')];
}

if (program.fix) {
  log.info('--fix does not work currently as eslint-plugin-json does not support it!');
}

eslintHelper(program);
