#!/usr/bin/env node
var CommanderWrapper = require('./utils/commander-wrapper');

var program = CommanderWrapper(function(commander) {
  return commander
    .command('sass', 'lint sass files')
    .command('all', 'run all css lint commands', {isDefault: true});
});
