#!/usr/bin/env node
var CommanderWrapper = require('./utils/commander-wrapper');
var config = require('./utils/get-config')();
var log = require('./utils/log');

var program = CommanderWrapper(function(commander) {
  return commander
    .command('css', 'lint css files')
    .command('sass', 'lint sass files')
    .command('all', 'run all css lint commands', {isDefault: true});
});

if (!config.css) {
  log.warn('CSS builds are turned off');
  process.exit();
}

