#!/usr/bin/env node
var CommanderWrapper = require('./utils/commander-wrapper');
var config = require('./utils/get-config')();
var log = require('./utils/log');

var program = CommanderWrapper(function(commander) {
  return commander
    .command('src', 'lint test source files')
    .command('all', 'run all test linters', {isDefault: true});
});

if (!config.test) {
  log.warn('Test builds are turned off');
  process.exit();
}

