#!/usr/bin/env node
var CommanderWrapper = require('./utils/commander-wrapper');

var program = CommanderWrapper(function(commander) {
  return commander
    .command('src', 'lint source lang files')
    .command('all', 'run all lang linters', {isDefault: true});
});
