#!/usr/bin/env node
var CommanderWrapper = require('./utils/commander-wrapper');

var program = CommanderWrapper(function(commander) {
  return commander
    .command('src', 'lint test source files')
    .command('all', 'run all test linters', {isDefault: true});
});
