#!/usr/bin/env node
var RunAll = require('./utils/run-all');
var CommanderWrapper = require('./utils/commander-wrapper');
var config = require('./utils/get-config')();

var program = CommanderWrapper(function(commander) {
  return commander
    .option('-w, --watch', 'watch files for changes and re-lint')
    .option('-e, --errors', 'only log errors')
    .option('-f, --fix', 'automatically fix semantic errors were possible');
});

var commands = [];
var args = [];

if (config.js) {
  commands.push(['sb-lint-js']);
}

if (config.css) {
  commands.push(['sb-lint-css-all']);
}

if (config.docs) {
  commands.push(['sb-lint-docs-all']);
}

if (config.lang) {
  commands.push(['sb-lint-lang']);
}

if (config.test) {
  commands.push(['sb-lint-test']);
}

if (program.errors) {
  args.push('--errors');
}
if (program.watch) {
  args.push('--watch');
}
if (program.fix) {
  args.push('--fix');
}

RunAll(commands, args);
