#!/usr/bin/env node
var eslintHelper = require('./utils/eslint-helper');
var exec = require('./utils/exec');
var CommanderWrapper = require('./utils/commander-wrapper');
var path = require('path');
var config = require('./utils/get-config')();

var program = CommanderWrapper(function(commander) {
  return commander
    .option('-w, --watch', 'watch files for changes and re-lint')
    .option('-e, --errors', 'only log errors')
    .option('-f, --fix', 'fix problems automatically')
    .arguments('<glob-or-file...>')
    .action(function(src) {
      this.src = src;
    });

});

if (!program.src) {
  program.src = [path.join(config.src, 'docs', '**', '*.md')];
}

exec(eslintHelper(program));
