#!/usr/bin/env node
var config = require('./utils/get-config')();

var program = require('commander')
  .version(config.sbVersion)
  .command('sass', 'lint sass files')
  .command('all', 'run all css lint commands', {isDefault: true})
  .parse(process.argv);
