#!/usr/bin/env node
var CommanderWrapper = require('./utils/commander-wrapper');

var program = CommanderWrapper(function(commander) {
  return commander
    .command('src', 'lint src js')
    .command('all', 'run all js linters', {isDefault: true});
});
