#!/usr/bin/env node
var CommanderWrapper = require('./utils/commander-wrapper');
var config = require('./utils/get-config')();
var log = require('./utils/log');

var program = CommanderWrapper(function(commander) {
  return commander
    .command('md', 'lint markdown files')
    .command('examples', 'lint js examples in markdown files')
    .command('all', 'run all', {isDefault: true});
});

if (!config.docs) {
  log.warn('Docs builds are turned off');
  process.exit();
}
