#!/usr/bin/env node
var config = require('./utils/get-config')();
var GetPath = require('./utils/get-path');
var path = require('path');
var shelljs = require('shelljs');

var program = require('commander')
  .version(config.spellbookVersion)
  .option('-p, --port <number>', 'what port to start the server on', parseInt)
  .option('-o, --open', 'open the server in your default browser')
  .option('-s, --sync', 'enable cross browser action sync')
  .option('-ui, --ui', 'enable browser-sync ui')
  .parse(process.argv);

var cmd = GetPath('browser-sync')
  + ' start'
  + ' --server'
  + ' --port ' + (program.port || config.port)
  + (program.ui ? '' : ' --no-ui')
  + (program.ghostMode ? '' : ' --no-ghost-mode')
  + (program.open ? '' : ' --no-open')
  + ' --files ' + path.join(config.dist, '**', '*.*');

console.log(cmd);
shelljs.exec(cmd);
/*
browserSync.init({
  server: config.path,
  port: program.port || config.port,
  ui: program.ui || false,
  ghostMode: program.sync || false,
  open: program.open || false,
  files: [
    path.join(config.dist, '**', '*.*'),
  ]
});*/
