#!/usr/bin/env node
var CommanderWrapper = require('./utils/commander-wrapper');

var program = CommanderWrapper(function(commander) {
  return commander
    .command('require', 'require main es5 file in node')
    .command('all', 'run all node tests', {isDefault: true});
});

