#!/usr/bin/env node
var CommanderWrapper = require('./utils/commander-wrapper');

var program = CommanderWrapper(function(commander) {
  return commander
    .option('-w, --watch', 'keep the tester running and run as things change');
});

log.fatal('Its not currently possible to run qunitjs tests in node...');
log.fatal('So we are just going to exit');
process.exit(1);
