#!/usr/bin/env node
var RunAll = require('./utils/run-all');
var CommanderWrapper = require('./utils/commander-wrapper');
var exec = require('./utils/exec');

var program = CommanderWrapper(function(commander) {
  return commander
    .option('-w, --watch', 'keep the tester running and run as things change');
});

exec('sb-build');

var commands = [
  ['sb-test-karma'],
];
var args = [];

if (program.watch) {
  args.push('--watch');
}

RunAll(commands, args);
