#!/usr/bin/env node
var config = require('./utils/config');
var PathExists = require('./utils/path-exists');
var path = require('path');
var GetPath = require('./utils/get-path');
var RunCommand = require('./utils/run-command');

var program = require('commander')
  .version(config.spellbookVersion)
  .arguments('[environments...]')
  .action(function(environments) {
    this.environments = environments;
  })
  .option('-w, --watch', 'keep the tester running and run as things change')
  .option('-a, --all', 'test in all possible environments')
  .parse(process.argv);

var browsers = [];
var others = [];

if (!program.environments) {
  program.environments = [];
  if (!program.all) {
    program.all = true;
  }
}

program.environments.forEach(function(environment) {
  if ((/chrome|ie|safari|firefox|node|browserify|webpack|rollup|all/i).test(environment)) {
    browsers.push(environment);
  } else if ((/node|browserify|webpack|rollup|all/i).test(environment)) {
    others.push(environment);
  } else {
    console.error('invalid environment ' + environment);
    process.exit(1);
  }
});

var KARMA_BROWSERS = ['Chrome', 'Firefox', 'IE', 'Safari'];

if (!PathExists(path.join(config.dist, 'test', 'bundle.js')) ||
    !PathExists(path.join(config.dist, 'browser', config.name + '.js'))) {
  RunCommand('exec', GetPath('sb-build-js'));
}

if (!PathExists(path.join(config.dist, 'browser', config.name + '.css'))) {
  RunCommand('exec', GetPath('sb-build-css'));
}


// TODO: how do we integrate this with spellbook-start (module.export?)
// TODO: test non-browser environments somehow
// http://localhost:9876/debug.html will be qunit UI
var options = {
  autoWatch: program.watch,
  singleRun: !program.watch,
};

var command = GetPath('karma')
  + ' start ' + GetPath('karma.config.js');

if (program.watch) {
  command += ' --auto-watch';
  command += ' --no-single-run';
}

RunCommand('exec', command);
