#!/usr/bin/env node
var config = require('./utils/get-config')();
var PathsExist = require('./utils/paths-exist');
var path = require('path');
var log = require('./utils/log');
var exec = require('./utils/exec');
var CommanderWrapper = require('./utils/commander-wrapper');

var program = CommanderWrapper(function(commander) {
  return commander
    .option('-w, --watch', 'keep the tester running and run as things change')
    .option('-b, --browsers', 'comma seperated list of browsers to run on');
});

var KARMA_BROWSERS = ['Chrome', 'Firefox', 'IE', 'Safari'];
var command = [
  'karma',
  'start',
  'karma.config.js'
];

if (program.watch) {
  command.push('--auto-watch');
  command.push('--no-single-run');
} else  {
  command.push('--no-auto-watch');
  command.push('--single-run');
}

if (program.browsers) {
  command.push('--browsers');
  command.push(program.browsers.join(','));
}

exec(command);
