#!/usr/bin/env node
var CommanderWrapper = require('./utils/commander-wrapper');

var program = CommanderWrapper(function(commander) {
  return commander
    .option('-w, --watch', 'keep the tester running and run as things change');
});

log.debug('Its not currently possible to run qunitjs tests in node...');
log.debug('So we are just going to exit');
process.exit(0);
