#!/usr/bin/env node
var RunAll = require('./utils/run-all');
var CommanderWrapper = require('./utils/commander-wrapper');
var exec = require('./utils/exec');

var program = CommanderWrapper(function(commander) {
  return commander
    .option('-w, --watch', 'keep the tester running and run as things change')
    .option('-n, --no-build', 'dont build before testing');
});

if (program.build) {
  exec('sb-build');
}

var commands = [
  ['sb-test-node'],
  ['sb-test-browser'],
];
var args = [];

if (program.watch) {
  args.push('--watch');
}

RunAll(commands, args);
