#!/usr/bin/env node
var Run = require('./utils/run');
var CommanderWrapper = require('./utils/commander-wrapper');

var program = CommanderWrapper(function(commander) {
  return commander;
});

var commands = [
  ['sb-build-all'],
  ['sb-lint-all'],
];
commands = commands.map(function(command) {
  command.push('--watch');
  return command;
});

setTimeout(function() {
  Run.one(['sb-test-all', '--no-build', '--no-lint', '--watch'], {nonFatal: true});
}, 9000);
Run.parallel(commands, {nonFatal: true});

