#!/usr/bin/env node
var Run = require('./utils/run');
var CommanderWrapper = require('./utils/commander-wrapper');

var program = CommanderWrapper(function(commander) {
  return commander
    .option('-p, --port <number>', 'what port to start the test server on', parseInt)
});

var commands = [
  ['sb-build-all'],
  ['sb-lint-all'],
];
commands = commands.map(function(command) {
  command.push('--watch');
  return command;
});

setTimeout(function() {
  var testCommand = ['sb-test-all', '--no-build', '--no-lint', '--watch'];
  if (program.port) {
    testCommand.push('--port');
    testCommand.push(program.port);
  }
  Run.one(testCommand, {nonFatal: true});
}, 9000);
Run.parallel(commands, {nonFatal: true});

